/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedDiagnoseRouteImport } from './routes/_authenticated/diagnose'
import { Route as AuthenticatedGardensRouteImport } from './routes/_authenticated/gardens'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedGardenGardenIdRouteImport } from './routes/_authenticated/garden.$gardenId'
import { Route as AuthenticatedGardensIndexRouteImport } from './routes/_authenticated/gardens.index'
import { Route as AuthenticatedGardensGardenIdRouteImport } from './routes/_authenticated/gardens.$gardenId'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs.index'
import { Route as AuthenticatedLogsNewRouteImport } from './routes/_authenticated/logs.new'
import { Route as AuthenticatedGardensGardenIdIndexRouteImport } from './routes/_authenticated/gardens.$gardenId.index'
import { Route as AuthenticatedGardensGardenIdExpensesRouteImport } from './routes/_authenticated/gardens.$gardenId.expenses'
import { Route as AuthenticatedGardensGardenIdJournalRouteImport } from './routes/_authenticated/gardens.$gardenId.journal'
import { Route as AuthenticatedGardensGardenIdLogsRouteImport } from './routes/_authenticated/gardens.$gardenId.logs'
import { Route as AuthenticatedGardensGardenIdPhotosRouteImport } from './routes/_authenticated/gardens.$gardenId.photos'
import { Route as AuthenticatedGardensGardenIdSettingsRouteImport } from './routes/_authenticated/gardens.$gardenId.settings'
import { Route as AuthenticatedGardensGardenIdTasksRouteImport } from './routes/_authenticated/gardens.$gardenId.tasks'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnoseRoute = AuthenticatedDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGardensRoute = AuthenticatedGardensRouteImport.update({
  id: '/gardens',
  path: '/gardens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGardenGardenIdRoute =
  AuthenticatedGardenGardenIdRouteImport.update({
    id: '/garden/$gardenId',
    path: '/garden/$gardenId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGardensIndexRoute =
  AuthenticatedGardensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGardensRoute,
  } as any)
const AuthenticatedGardensGardenIdRoute =
  AuthenticatedGardensGardenIdRouteImport.update({
    id: '/$gardenId',
    path: '/$gardenId',
    getParentRoute: () => AuthenticatedGardensRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsNewRoute = AuthenticatedLogsNewRouteImport.update({
  id: '/logs/new',
  path: '/logs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGardensGardenIdIndexRoute =
  AuthenticatedGardensGardenIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGardensGardenIdRoute,
  } as any)
const AuthenticatedGardensGardenIdExpensesRoute =
  AuthenticatedGardensGardenIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedGardensGardenIdRoute,
  } as any)
const AuthenticatedGardensGardenIdJournalRoute =
  AuthenticatedGardensGardenIdJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedGardensGardenIdRoute,
  } as any)
const AuthenticatedGardensGardenIdLogsRoute =
  AuthenticatedGardensGardenIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedGardensGardenIdRoute,
  } as any)
const AuthenticatedGardensGardenIdPhotosRoute =
  AuthenticatedGardensGardenIdPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedGardensGardenIdRoute,
  } as any)
const AuthenticatedGardensGardenIdSettingsRoute =
  AuthenticatedGardensGardenIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedGardensGardenIdRoute,
  } as any)
const AuthenticatedGardensGardenIdTasksRoute =
  AuthenticatedGardensGardenIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedGardensGardenIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/gardens': typeof AuthenticatedGardensRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/garden/$gardenId': typeof AuthenticatedGardenGardenIdRoute
  '/gardens/$gardenId': typeof AuthenticatedGardensGardenIdRouteWithChildren
  '/logs/new': typeof AuthenticatedLogsNewRoute
  '/gardens/': typeof AuthenticatedGardensIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/gardens/$gardenId/expenses': typeof AuthenticatedGardensGardenIdExpensesRoute
  '/gardens/$gardenId/journal': typeof AuthenticatedGardensGardenIdJournalRoute
  '/gardens/$gardenId/logs': typeof AuthenticatedGardensGardenIdLogsRoute
  '/gardens/$gardenId/photos': typeof AuthenticatedGardensGardenIdPhotosRoute
  '/gardens/$gardenId/settings': typeof AuthenticatedGardensGardenIdSettingsRoute
  '/gardens/$gardenId/tasks': typeof AuthenticatedGardensGardenIdTasksRoute
  '/gardens/$gardenId/': typeof AuthenticatedGardensGardenIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/': typeof AuthenticatedIndexRoute
  '/garden/$gardenId': typeof AuthenticatedGardenGardenIdRoute
  '/logs/new': typeof AuthenticatedLogsNewRoute
  '/gardens': typeof AuthenticatedGardensIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/gardens/$gardenId/expenses': typeof AuthenticatedGardensGardenIdExpensesRoute
  '/gardens/$gardenId/journal': typeof AuthenticatedGardensGardenIdJournalRoute
  '/gardens/$gardenId/logs': typeof AuthenticatedGardensGardenIdLogsRoute
  '/gardens/$gardenId/photos': typeof AuthenticatedGardensGardenIdPhotosRoute
  '/gardens/$gardenId/settings': typeof AuthenticatedGardensGardenIdSettingsRoute
  '/gardens/$gardenId/tasks': typeof AuthenticatedGardensGardenIdTasksRoute
  '/gardens/$gardenId': typeof AuthenticatedGardensGardenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/diagnose': typeof AuthenticatedDiagnoseRoute
  '/_authenticated/gardens': typeof AuthenticatedGardensRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/garden/$gardenId': typeof AuthenticatedGardenGardenIdRoute
  '/_authenticated/gardens/$gardenId': typeof AuthenticatedGardensGardenIdRouteWithChildren
  '/_authenticated/logs/new': typeof AuthenticatedLogsNewRoute
  '/_authenticated/gardens/': typeof AuthenticatedGardensIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/gardens/$gardenId/expenses': typeof AuthenticatedGardensGardenIdExpensesRoute
  '/_authenticated/gardens/$gardenId/journal': typeof AuthenticatedGardensGardenIdJournalRoute
  '/_authenticated/gardens/$gardenId/logs': typeof AuthenticatedGardensGardenIdLogsRoute
  '/_authenticated/gardens/$gardenId/photos': typeof AuthenticatedGardensGardenIdPhotosRoute
  '/_authenticated/gardens/$gardenId/settings': typeof AuthenticatedGardensGardenIdSettingsRoute
  '/_authenticated/gardens/$gardenId/tasks': typeof AuthenticatedGardensGardenIdTasksRoute
  '/_authenticated/gardens/$gardenId/': typeof AuthenticatedGardensGardenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/diagnose'
    | '/gardens'
    | '/inventory'
    | '/reports'
    | '/weather'
    | '/garden/$gardenId'
    | '/gardens/$gardenId'
    | '/logs/new'
    | '/gardens/'
    | '/logs/'
    | '/gardens/$gardenId/expenses'
    | '/gardens/$gardenId/journal'
    | '/gardens/$gardenId/logs'
    | '/gardens/$gardenId/photos'
    | '/gardens/$gardenId/settings'
    | '/gardens/$gardenId/tasks'
    | '/gardens/$gardenId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assistant'
    | '/diagnose'
    | '/inventory'
    | '/reports'
    | '/weather'
    | '/'
    | '/garden/$gardenId'
    | '/logs/new'
    | '/gardens'
    | '/logs'
    | '/gardens/$gardenId/expenses'
    | '/gardens/$gardenId/journal'
    | '/gardens/$gardenId/logs'
    | '/gardens/$gardenId/photos'
    | '/gardens/$gardenId/settings'
    | '/gardens/$gardenId/tasks'
    | '/gardens/$gardenId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/diagnose'
    | '/_authenticated/gardens'
    | '/_authenticated/inventory'
    | '/_authenticated/reports'
    | '/_authenticated/weather'
    | '/_authenticated/'
    | '/_authenticated/garden/$gardenId'
    | '/_authenticated/gardens/$gardenId'
    | '/_authenticated/logs/new'
    | '/_authenticated/gardens/'
    | '/_authenticated/logs/'
    | '/_authenticated/gardens/$gardenId/expenses'
    | '/_authenticated/gardens/$gardenId/journal'
    | '/_authenticated/gardens/$gardenId/logs'
    | '/_authenticated/gardens/$gardenId/photos'
    | '/_authenticated/gardens/$gardenId/settings'
    | '/_authenticated/gardens/$gardenId/tasks'
    | '/_authenticated/gardens/$gardenId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnose': {
      id: '/_authenticated/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof AuthenticatedDiagnoseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gardens': {
      id: '/_authenticated/gardens'
      path: '/gardens'
      fullPath: '/gardens'
      preLoaderRoute: typeof AuthenticatedGardensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garden/$gardenId': {
      id: '/_authenticated/garden/$gardenId'
      path: '/garden/$gardenId'
      fullPath: '/garden/$gardenId'
      preLoaderRoute: typeof AuthenticatedGardenGardenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gardens/': {
      id: '/_authenticated/gardens/'
      path: '/'
      fullPath: '/gardens/'
      preLoaderRoute: typeof AuthenticatedGardensIndexRouteImport
      parentRoute: typeof AuthenticatedGardensRoute
    }
    '/_authenticated/gardens/$gardenId': {
      id: '/_authenticated/gardens/$gardenId'
      path: '/$gardenId'
      fullPath: '/gardens/$gardenId'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdRouteImport
      parentRoute: typeof AuthenticatedGardensRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/new': {
      id: '/_authenticated/logs/new'
      path: '/logs/new'
      fullPath: '/logs/new'
      preLoaderRoute: typeof AuthenticatedLogsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gardens/$gardenId/': {
      id: '/_authenticated/gardens/$gardenId/'
      path: '/'
      fullPath: '/gardens/$gardenId/'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdIndexRouteImport
      parentRoute: typeof AuthenticatedGardensGardenIdRoute
    }
    '/_authenticated/gardens/$gardenId/expenses': {
      id: '/_authenticated/gardens/$gardenId/expenses'
      path: '/expenses'
      fullPath: '/gardens/$gardenId/expenses'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdExpensesRouteImport
      parentRoute: typeof AuthenticatedGardensGardenIdRoute
    }
    '/_authenticated/gardens/$gardenId/journal': {
      id: '/_authenticated/gardens/$gardenId/journal'
      path: '/journal'
      fullPath: '/gardens/$gardenId/journal'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdJournalRouteImport
      parentRoute: typeof AuthenticatedGardensGardenIdRoute
    }
    '/_authenticated/gardens/$gardenId/logs': {
      id: '/_authenticated/gardens/$gardenId/logs'
      path: '/logs'
      fullPath: '/gardens/$gardenId/logs'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdLogsRouteImport
      parentRoute: typeof AuthenticatedGardensGardenIdRoute
    }
    '/_authenticated/gardens/$gardenId/photos': {
      id: '/_authenticated/gardens/$gardenId/photos'
      path: '/photos'
      fullPath: '/gardens/$gardenId/photos'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdPhotosRouteImport
      parentRoute: typeof AuthenticatedGardensGardenIdRoute
    }
    '/_authenticated/gardens/$gardenId/settings': {
      id: '/_authenticated/gardens/$gardenId/settings'
      path: '/settings'
      fullPath: '/gardens/$gardenId/settings'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdSettingsRouteImport
      parentRoute: typeof AuthenticatedGardensGardenIdRoute
    }
    '/_authenticated/gardens/$gardenId/tasks': {
      id: '/_authenticated/gardens/$gardenId/tasks'
      path: '/tasks'
      fullPath: '/gardens/$gardenId/tasks'
      preLoaderRoute: typeof AuthenticatedGardensGardenIdTasksRouteImport
      parentRoute: typeof AuthenticatedGardensGardenIdRoute
    }
  }
}

interface AuthenticatedGardensGardenIdRouteChildren {
  AuthenticatedGardensGardenIdExpensesRoute: typeof AuthenticatedGardensGardenIdExpensesRoute
  AuthenticatedGardensGardenIdJournalRoute: typeof AuthenticatedGardensGardenIdJournalRoute
  AuthenticatedGardensGardenIdLogsRoute: typeof AuthenticatedGardensGardenIdLogsRoute
  AuthenticatedGardensGardenIdPhotosRoute: typeof AuthenticatedGardensGardenIdPhotosRoute
  AuthenticatedGardensGardenIdSettingsRoute: typeof AuthenticatedGardensGardenIdSettingsRoute
  AuthenticatedGardensGardenIdTasksRoute: typeof AuthenticatedGardensGardenIdTasksRoute
  AuthenticatedGardensGardenIdIndexRoute: typeof AuthenticatedGardensGardenIdIndexRoute
}

const AuthenticatedGardensGardenIdRouteChildren: AuthenticatedGardensGardenIdRouteChildren =
  {
    AuthenticatedGardensGardenIdExpensesRoute:
      AuthenticatedGardensGardenIdExpensesRoute,
    AuthenticatedGardensGardenIdJournalRoute:
      AuthenticatedGardensGardenIdJournalRoute,
    AuthenticatedGardensGardenIdLogsRoute:
      AuthenticatedGardensGardenIdLogsRoute,
    AuthenticatedGardensGardenIdPhotosRoute:
      AuthenticatedGardensGardenIdPhotosRoute,
    AuthenticatedGardensGardenIdSettingsRoute:
      AuthenticatedGardensGardenIdSettingsRoute,
    AuthenticatedGardensGardenIdTasksRoute:
      AuthenticatedGardensGardenIdTasksRoute,
    AuthenticatedGardensGardenIdIndexRoute:
      AuthenticatedGardensGardenIdIndexRoute,
  }

const AuthenticatedGardensGardenIdRouteWithChildren =
  AuthenticatedGardensGardenIdRoute._addFileChildren(
    AuthenticatedGardensGardenIdRouteChildren,
  )

interface AuthenticatedGardensRouteChildren {
  AuthenticatedGardensGardenIdRoute: typeof AuthenticatedGardensGardenIdRouteWithChildren
  AuthenticatedGardensIndexRoute: typeof AuthenticatedGardensIndexRoute
}

const AuthenticatedGardensRouteChildren: AuthenticatedGardensRouteChildren = {
  AuthenticatedGardensGardenIdRoute:
    AuthenticatedGardensGardenIdRouteWithChildren,
  AuthenticatedGardensIndexRoute: AuthenticatedGardensIndexRoute,
}

const AuthenticatedGardensRouteWithChildren =
  AuthenticatedGardensRoute._addFileChildren(AuthenticatedGardensRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDiagnoseRoute: typeof AuthenticatedDiagnoseRoute
  AuthenticatedGardensRoute: typeof AuthenticatedGardensRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGardenGardenIdRoute: typeof AuthenticatedGardenGardenIdRoute
  AuthenticatedLogsNewRoute: typeof AuthenticatedLogsNewRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDiagnoseRoute: AuthenticatedDiagnoseRoute,
  AuthenticatedGardensRoute: AuthenticatedGardensRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGardenGardenIdRoute: AuthenticatedGardenGardenIdRoute,
  AuthenticatedLogsNewRoute: AuthenticatedLogsNewRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
